name: Image Dev

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile.dev"
      - ".github/workflows/image-dev.yaml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  QUARTO_VERSION: 1.9.36

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile.dev
          push: true
          build-args: |
            QUARTO_VERSION=${{ env.QUARTO_VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/unitn-hci-gp-dev:latest
            ghcr.io/${{ github.repository_owner }}/unitn-hci-gp-dev:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/unitn-hci-gp-dev:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/unitn-hci-gp-dev:cache,mode=max
